--- 
url: http://localhost:3000
master_app_url: http://app-test.veecue.com/el_user
master_app: el_user
base_url: http://app-test.veecue.com/
api: 
  url: 
    active_register_code_path: /register_codes/active
readonly_for_test: 
  lessons: 
    string: name
cached_config: 
  el_user: 
    api: |
      --- 
      url: 
        signin: /signin
        signout: /signout
        update_password_service: /password_services/0
        update_profile_service: /profile_services/0
        profile_service: /profile_services
        session_service: /session_services
        forgot_password: /passwords/forgot
        create_partner_sessions_path: /partner_sessions
        login_partner_sessions_path: /partner_sessions/login

    url: http://app-test.veecue.com/el_user
    database: |
      --- 
      production: 
        adapter: mysql2
        database: v3_el_user_production
        username: veecue
        password: xoUphL8d
        host: db1.lan
        pool: 10
        encoding: utf8

  ellis: 
    api: |
      --- !map:ActiveSupport::HashWithIndifferentAccess 
      url: !map:ActiveSupport::HashWithIndifferentAccess 
        lesson: /content/lessons/:lesson_id

    url: http://app-test.veecue.com/ellis
    database: |
      --- !map:ActiveSupport::HashWithIndifferentAccess 
      production: !map:ActiveSupport::HashWithIndifferentAccess 
        adapter: mysql2
        database: v3_el_ellis_production
        username: veecue
        password: xoUphL8d
        host: db1.lan
        pool: 10
        encoding: utf8

